# Generated by Django 3.0.2 on 2020-03-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0002_auto_20200310_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intersection',
            name='as_date',
            field=models.DateField(verbose_name='기술 지원 날짜'),
        ),
        migrations.AlterField(
            model_name='intersection',
            name='make_date',
            field=models.DateField(verbose_name='제조년월일'),
        ),
    ]
