# Generated by Django 3.0.2 on 2020-03-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0004_auto_20200317_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intersection',
            name='description',
            field=models.TextField(blank=True, help_text='현장에서 촬영된 사진(GPS 정보 포함)', verbose_name='사진 설명'),
        ),
    ]
