# Generated by Django 3.0.2 on 2020-03-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0006_auto_20200318_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='intersection',
            name='orientation',
            field=models.IntegerField(default=0, verbose_name='사진 방향 정보'),
        ),
        migrations.AlterField(
            model_name='intersection',
            name='bd_ins_kind',
            field=models.CharField(max_length=64, verbose_name='보드 실장 상태'),
        ),
    ]
