# Generated by Django 3.0.2 on 2020-04-27 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0011_aslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aslog',
            name='city_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='city2.City'),
            preserve_default=False,
        ),
    ]
