# Generated by Django 3.0.2 on 2020-04-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0012_aslog_city_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aslog',
            name='title',
            field=models.CharField(max_length=50, verbose_name='증상'),
        ),
    ]
