# Generated by Django 3.0.2 on 2020-04-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0014_intersection_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aslog',
            name='content',
            field=models.TextField(max_length=300, verbose_name='세부 정보'),
        ),
    ]
