# Generated by Django 3.0.2 on 2020-04-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0018_auto_20200429_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aslog',
            old_name='contents',
            new_name='detail_info',
        ),
    ]
