# Generated by Django 3.0.2 on 2020-05-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0021_auto_20200515_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aslog',
            name='description',
            field=models.CharField(blank=True, help_text='A/S 관련 간단한 한 줄 설명', max_length=100, verbose_name='조치'),
        ),
    ]
