# Generated by Django 3.0.2 on 2020-05-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0025_auto_20200526_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intersection',
            name='cpu_version',
            field=models.CharField(max_length=32, verbose_name='CPU 버전'),
        ),
    ]
