# Generated by Django 3.0.2 on 2020-05-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0030_auto_20200527_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intersection',
            name='man_company',
            field=models.CharField(choices=[('서돌전자통신', '서돌전자통신'), ('코스텍', '코스텍'), ('세인시스템', '세인시스템'), ('엘케이일레븐', '엘케이일레븐'), ('한국전기교통', '한국전기교통'), ('진우산전', '진우산전'), ('(주)신호', '(주)신호'), ('진우전자', '진우전자'), ('양광', '양광'), ('옵토피아', '옵토피아'), ('포에프', '포에프'), ('태경', '태경'), ('고엽제', '고엽제'), ('대한신호', '대한신호'), ('기타', '기타')], max_length=64, verbose_name='제조사'),
        ),
        migrations.AlterField(
            model_name='intersection',
            name='model_name',
            field=models.CharField(choices=[('SEC-N9400', 'SEC-N9400'), ('SEC-N9500', 'SEC-N9500'), ('SEC-P9600', 'SEC-P9600'), ('CJH-1000', 'CJH-1000'), ('COEL-TSC100', 'COEL-TSC100'), ('JWS-7000-S', 'JWS-7000-S'), ('KET-2100', 'KET-2100'), ('KAOVA-STC', 'KAOVA-STC'), ('KSC-5800SE', 'KSC-5800SE'), ('MIT-9000S', 'MIT-9000S'), ('OPT-9000A', 'OPT-9000A'), ('OPT-9200S', 'OPT-9200S'), ('OT-2000', 'OT-2000'), ('STLC-S01', 'STLC-S01'), ('SDS-9000', 'SDS-9000'), ('SDS-9000B', 'SDS-9000B'), ('TC-9000A', 'TC-9000A'), ('TG-7000S', 'TG-7000S'), ('UKET-2100', 'UKET-2100'), ('Y-6000', 'Y-6000'), ('YK-6000', 'YK-6000'), ('기타', '기타')], max_length=64, verbose_name='모델명'),
        ),
    ]
