# Generated by Django 3.0.2 on 2020-06-08 15:22

import city2.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0032_auto_20200608_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='intersection',
            name='image2',
            field=city2.fields.ThumbnailImageField(default=1, upload_to='photo/%Y/%m'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='기타 설명'),
        ),
    ]
