# Generated by Django 3.0.2 on 2020-06-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0035_auto_20200608_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intersection',
            name='orientation',
            field=models.IntegerField(default=0, verbose_name='사진 방향 정보'),
        ),
    ]
