# Generated by Django 3.0.2 on 2020-06-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0040_auto_20200612_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(default=1, verbose_name='GPS 위도'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(default=1, verbose_name='GPS 경도'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='zoom',
            field=models.IntegerField(default=1.0, verbose_name='Zoom'),
            preserve_default=False,
        ),
    ]
