# Generated by Django 3.0.2 on 2020-07-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0056_auto_20200721_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intersection',
            name='model_name',
            field=models.CharField(choices=[('SEC-9000', 'SEC-9000'), ('SEC-N9000', 'SEC-N9000'), ('SEC-N9400', 'SEC-N9400'), ('SEC-S9400', 'SEC-S9400'), ('SEC-N9500', 'SEC-N9500'), ('SEC-P9600', 'SEC-P9600'), ('COEL-TSC100', 'COEL-TSC100'), ('COEL-TSC200', 'COEL-TSC200'), ('COEL-TS-500', 'COEL-TS-500'), ('COEL-TSC1000', 'COEL-TSC1000'), ('CJH-1000', 'CJH-1000'), ('CTSC-3000', 'CTSC-3000'), ('CTSC-3000-BS', 'CTSC-3000-BS'), ('DJ-7000', 'DJ-7000'), ('DS-1000', 'DS-1000'), ('DS-2000', 'DS-2000'), ('EST-5000A', 'EST-5000A'), ('GSC-A1', 'GSC-A1'), ('GTL-TSC100', 'GTL-TSC100'), ('HJ-5000', 'HJ-5000'), ('HJ-5000H', 'HJ-5000H'), ('HJ-5000T', 'HJ-5000T'), ('HTC-7100A', 'HTC-7100A'), ('ILT-TSC-100S', 'ILT-TSC-100S'), ('IT-1600', 'IT-1600'), ('JM-100', 'JM-100'), ('JW-7000', 'JW-7000'), ('JW-7000A', 'JW-7000A'), ('JW-7000-S', 'JW-7000-S'), ('JWS-7000-S', 'JWS-7000-S'), ('JWI-8000', 'JWI-8000'), ('JWIS-8000', 'JWIS-8000'), ('JWIS-9600', 'JWIS-9600'), ('JWTC-LC-G01', 'JWTC-LC-G01'), ('KCL-5000A', 'KCL-5000A'), ('KET-2100', 'KET-2100'), ('KET-2100N', 'KET-2100N'), ('KET-3100MA', 'KET-3100MA'), ('KET-3100SB', 'KET-3100SB'), ('KAOVA-STC', 'KAOVA-STC'), ('KSC-2800', 'KSC-2800'), ('KSC-2800S', 'KSC-2800S'), ('KSC-5800S', 'KSC-5800S'), ('KSC-5800SE', 'KSC-5800SE'), ('LK-3100', 'LK-3100'), ('LK-4000', 'LK-4000'), ('LTK-2000', 'LTK-2000'), ('MIT-9000S', 'MIT-9000S'), ('MS-A2000', 'MS-A2000'), ('NI-2000', 'NI-2000'), ('OPT-5000', 'OPT-5000'), ('OPT-9000A', 'OPT-9000A'), ('OPT-9200S', 'OPT-9200S'), ('OT-2000', 'OT-2000'), ('PS-9000', 'PS-2000'), ('Road-5000', 'Road-5000'), ('SDS-9000', 'SDS-9000'), ('SDS-9000A', 'SDS-9000A'), ('SDS-9000B', 'SDS-9000B'), ('SDS-9000S', 'SDS-9000S'), ('SJS-2000', 'SJS-2000'), ('SJS-3000', 'SJS-3000'), ('SLC-S2000', 'SLC-S2000'), ('SLC-S2000-(A)', 'SLC-S2000-(A)'), ('SLC-S3000', 'SLC-S3000'), ('SLC-S5000', 'SLC-S5000'), ('SMS-5000', 'SMS-5000'), ('SMS-5000-SB', 'SMS-5000-SB'), ('ST-09SL', 'ST-09SL'), ('ST-09ST-D', 'ST-09ST-D'), ('STC-3000', 'STC-3000'), ('STCM-SBB4', 'STCM-SBB4'), ('STE-8000', 'STE-8000'), ('STLC-S01', 'STLC-S01'), ('STLC-S2', 'STLC-S2'), ('STLC-S2-(2)', 'STLC-S2-(2)'), ('STLC-S3', 'STLC-S3'), ('STS045', 'STS045'), ('STS-046', 'STS-046'), ('TC-9000A', 'TC-9000A'), ('TG-7000S', 'TG-7000S'), ('TG-7000SS', 'TG-7000SS'), ('TYS-1000', 'TYS-1000'), ('UKET-2100', 'UKET-2100'), ('UKET-3100SB', 'UKET-3100SB'), ('WH-100', 'WH-100'), ('WS-2300', 'WS-2300'), ('Y-6000', 'Y-6000'), ('Y-6000A', 'Y-6000A'), ('Y-8000', 'Y-8000'), ('Y-8000A', 'Y-8000A'), ('YG-5000', 'YG-5000'), ('YK-5000', 'YK-5000'), ('YK-6000', 'YK-6000'), ('YK-6000B', 'YK-6000B'), ('ZEO-TSC-601', 'ZEO-TSC-601'), ('기타', '기타')], max_length=64, verbose_name='모델명'),
        ),
    ]
