# Generated by Django 3.0.2 on 2020-09-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0063_auto_20200918_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='aslog',
            name='reporter',
            field=models.CharField(default=1, max_length=64, verbose_name='신고자'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aslog',
            name='title',
            field=models.CharField(max_length=128, verbose_name='증상'),
        ),
    ]
