# Generated by Django 3.0.2 on 2020-03-10 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intersection',
            name='int_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='city2.City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intersection',
            name='int_name',
            field=models.CharField(max_length=64, verbose_name='교차로명'),
        ),
    ]
