# Generated by Django 3.0.2 on 2020-03-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0005_auto_20200318_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intersection',
            name='description',
            field=models.TextField(blank=True, help_text='추가로 기입하고자 하는 정보들 설정', verbose_name='기타 정보'),
        ),
    ]
