# Generated by Django 3.0.2 on 2020-05-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0020_remove_intersection_as_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='상세 설명'),
        ),
        migrations.AlterField(
            model_name='intersection',
            name='product_type',
            field=models.CharField(choices=[('교통신호제어기', '교통신호제어기'), ('영상검지기', '영상검지기'), ('루프검지기', '루프검지기'), ('VDU(좌회전 감응)', 'VDU(좌회전 감응)'), ('보행자작동신호기', '보행자작동신호기')], max_length=64, verbose_name='장비 타입'),
        ),
    ]
