# Generated by Django 3.0.2 on 2020-05-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0026_auto_20200526_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aslog',
            name='slug',
        ),
    ]
