# Generated by Django 3.0.2 on 2020-06-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0033_auto_20200608_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='intersection',
            name='orientation2',
            field=models.IntegerField(default=0, verbose_name='사진 방향 정보(2)'),
        ),
        migrations.AlterField(
            model_name='intersection',
            name='orientation',
            field=models.IntegerField(default=0, verbose_name='사진 방향 정보(1)'),
        ),
    ]
