# Generated by Django 3.0.2 on 2020-06-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0034_auto_20200608_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intersection',
            name='latitude',
            field=models.FloatField(verbose_name='GPS 위도'),
        ),
        migrations.AlterField(
            model_name='intersection',
            name='longitude',
            field=models.FloatField(verbose_name='GPS 경도'),
        ),
    ]
