# Generated by Django 3.0.2 on 2020-06-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0046_auto_20200624_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dust',
            name='create_dt',
            field=models.DateTimeField(verbose_name='수집시점'),
        ),
    ]
