# Generated by Django 3.0.2 on 2020-06-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0047_auto_20200624_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dust',
            options={'ordering': ('log_datetime',)},
        ),
        migrations.RenameField(
            model_name='dust',
            old_name='create_dt',
            new_name='log_datetime',
        ),
    ]
