# Generated by Django 3.0.2 on 2020-09-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0059_auto_20200828_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='aslog',
            name='as_date',
            field=models.DateField(default=1, verbose_name='현장 조치 날짜'),
            preserve_default=False,
        ),
    ]
