# Generated by Django 3.0.2 on 2020-09-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city2', '0060_aslog_as_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aslog',
            name='as_date',
        ),
    ]
